const steps=[
 {id:'context',t:'Контекст',s:'Запрос и история'}, {id:'point',t:'Точка А',s:'Где я сегодня'}, {id:'career',t:'Опыт',s:'Профессиональный путь'}, {id:'wins',t:'Победы',s:'Суперсилы'}, {id:'lives',t:'10 жизней',s:'Интересы и условия'}, {id:'people',t:'Окружение',s:'Взгляд со стороны'}, {id:'tests',t:'Доп. данные',s:'Тесты и ценности'}, {id:'criteria',t:'Фильтр работы',s:'Моё / не моё'}, {id:'report',t:'Итог',s:'Гипотезы и план'}
];
const pointQuestions=[
 'Понимаю, кем хочу быть и куда иду','Знаю свои таланты, сильные стороны и на что опираться','Осознаю ценность своего опыта и право на достойный доход','Опираюсь на своё мнение и выбираю то, что нравится мне','Чётко вижу критерии подходящей мне работы','Могу легко сформулировать, кто я и в чём моя польза','Понимаю первые шаги: что делать завтра и через неделю','У меня достаточно сил и желания действовать','Интерес к новому сильнее страха ошибок','Умею переключаться и отдыхать без чувства вины'
];
const criteria=[
 {id:'investigate',label:'Работа похожа на разгадку: разобраться в запутанном, докопаться до причины'},
 {id:'visible',label:'Виден результат по ходу дела: сделал — и понятно, что получилось'},
 {id:'help',label:'Я вижу, какому человеку и чем именно помог'},
 {id:'deep',label:'Можно целиком погружаться в одну задачу, а не жить в постоянной многозадачности'},
 {id:'oneone',label:'Общение в основном один на один или в маленькой группе, и его объём можно регулировать'},
 {id:'teach',label:'Можно объяснять и показывать другим то, что сам понял'},
 {id:'novelty',label:'Регулярно появляются новые случаи, задачи или темы'},
 {id:'ownership',label:'Есть свой понятный участок ответственности, без роли «человек-оркестр»'},
 {id:'autonomy',label:'Можно самому выбирать способ выполнения задачи без контроля каждого шага'},
 {id:'portable',label:'Профессию можно «забрать с собой» — работать из другого города или страны'}
];
const defaultState={data:{},points:pointQuestions.map(()=>({score:5,why:'',ten:''})),jobs:[{},{}],wins:[{},{},{}],lives:[{},{},{}],people:[{},{}],criteria:Object.fromEntries(criteria.map(c=>[c.id,3]))};
let state=load()||structuredClone(defaultState);let current=0,saveTimer;
function load(){try{return JSON.parse(localStorage.getItem('careerNavigatorV1'))}catch(e){return null}}
function save(){localStorage.setItem('careerNavigatorV1',JSON.stringify(state));document.getElementById('saveState').textContent='Сохранено в браузере · '+new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});calcProgress()}
function scheduleSave(){clearTimeout(saveTimer);document.getElementById('saveState').textContent='Сохраняю…';saveTimer=setTimeout(save,250)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function nav(){const n=document.getElementById('stepnav');n.innerHTML=steps.map((x,i)=>`<button class="stepbtn ${i===current?'active':''}" data-step="${i}"><span class="stepnum">${i+1}</span><span class="steptext">${x.t}<small>${x.s}</small></span></button>`).join('');n.querySelectorAll('.stepbtn').forEach(b=>b.onclick=()=>go(+b.dataset.step))}
function go(i){current=Math.max(0,Math.min(steps.length-1,i));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.getElementById('panel-'+steps[current].id).classList.add('active');nav();if(steps[current].id==='report')renderReport();window.scrollTo({top:document.querySelector('.mainGrid').offsetTop-70,behavior:'smooth'});calcProgress()}
function calcProgress(){let total=0,filled=0;document.querySelectorAll('[data-k]').forEach(el=>{total++;if(String(state.data[el.dataset.k]||'').trim())filled++});['jobs','wins','lives','people'].forEach(k=>state[k].forEach(o=>Object.values(o).forEach(v=>{total++;if(String(v||'').trim())filled++})));const pct=Math.max(Math.round(filled/Math.max(1,total)*100),Math.round(current/(steps.length-1)*100));document.getElementById('progressbar').style.width=pct+'%'}
function bindStatic(){document.querySelectorAll('[data-k]').forEach(el=>{el.value=state.data[el.dataset.k]||'';el.addEventListener('input',()=>{state.data[el.dataset.k]=el.value;scheduleSave()})});document.querySelectorAll('.next').forEach(b=>b.onclick=()=>go(current+1));document.querySelectorAll('.prev').forEach(b=>b.onclick=()=>go(current-1));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const k=b.dataset.add;if(k==='lives'&&state[k].length>=10)return;state[k].push({});renderRepeats();scheduleSave()})}
function renderPoints(){document.getElementById('pointRows').innerHTML=pointQuestions.map((q,i)=>`<div class="scaleRow"><div class="qtitle">${i+1}. ${q}</div><div class="rangeBox"><div class="scoreBubble" id="score${i}">${state.points[i]?.score??5}</div><input type="range" min="0" max="10" value="${state.points[i]?.score??5}" data-point="${i}" data-f="score"></div><textarea class="smallarea" placeholder="Почему такой балл?" data-point="${i}" data-f="why">${esc(state.points[i]?.why||'')}</textarea><textarea class="smallarea" placeholder="Что будет на 10 из 10?" data-point="${i}" data-f="ten">${esc(state.points[i]?.ten||'')}</textarea></div>`).join('');document.querySelectorAll('[data-point]').forEach(el=>el.oninput=()=>{const i=+el.dataset.point;state.points[i]=state.points[i]||{};state.points[i][el.dataset.f]=el.type==='range'?+el.value:el.value;if(el.type==='range')document.getElementById('score'+i).textContent=el.value;scheduleSave()})}
const repeatDefs={
 jobs:{title:'Опыт',fields:[['role','Период / компания / роль','input'],['liked','Что делали с удовольствием? От каких задач время летело?','textarea'],['disliked','Что откладывали, что раздражало или пугало?','textarea'],['left','Почему ушли / хотите уйти на самом деле?','textarea'],['lesson','Главный урок о себе из этого опыта','textarea']]},
 wins:{title:'Победа',fields:[['event','Что это было за событие?','textarea'],['liked','Что в процессе особенно нравилось?','textarea'],['how','Как именно вы это сделали? За счёт чего получилось?','textarea'],['obstacle','С чем пришлось справиться?','textarea'],['whywin','Почему это для вас победа?','textarea']]},
 lives:{title:'Жизнь',fields:[['role','Роль / образ','input'],['verbs','Какие 3 действия вы хотите делать в этой роли?','textarea'],['conditions','Что должно быть вокруг, чтобы вам было хорошо?','textarea']]},
 people:{title:'Человек',fields:[['person','Кто это и из какой сферы жизни?','input'],['strengths','Что мне нравится делать? В чём я силён? Чему у меня можно научиться?','textarea'],['association','С кем / чем я ассоциируюсь и почему?','textarea']]}
};
function renderRepeats(){Object.keys(repeatDefs).forEach(k=>{const d=repeatDefs[k],host=document.getElementById(k);host.innerHTML=state[k].map((o,i)=>`<div class="repeatCard"><div class="repeatHead"><strong>${d.title} ${i+1}</strong>${state[k].length>1?`<button class="remove" data-rm="${k}" data-i="${i}">Удалить</button>`:''}</div>${d.fields.map(f=>`<div class="field"><label>${f[1]}</label>${f[2]==='input'?`<input class="input" data-rep="${k}" data-i="${i}" data-f="${f[0]}" value="${esc(o[f[0]]||'')}">`:`<textarea class="smallarea" data-rep="${k}" data-i="${i}" data-f="${f[0]}">${esc(o[f[0]]||'')}</textarea>`}</div>`).join('')}</div>`).join('')});document.querySelectorAll('[data-rep]').forEach(el=>el.oninput=()=>{state[el.dataset.rep][+el.dataset.i][el.dataset.f]=el.value;scheduleSave()});document.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{state[b.dataset.rm].splice(+b.dataset.i,1);renderRepeats();scheduleSave()})}
function renderCriteria(){document.getElementById('criteriaRows').innerHTML=criteria.map((c,i)=>`<div class="criteriaRow"><label>${i+1}. ${c.label}</label><div class="importance"><input type="range" min="0" max="5" value="${state.criteria[c.id]??3}" data-crit="${c.id}"><strong id="crit-${c.id}">${state.criteria[c.id]??3}</strong></div></div>`).join('');document.querySelectorAll('[data-crit]').forEach(el=>el.oninput=()=>{state.criteria[el.dataset.crit]=+el.value;document.getElementById('crit-'+el.dataset.crit).textContent=el.value;scheduleSave()})}