const roles=[
{name:'Карьерный консультант / профориентолог',desc:'Разбор опыта, мотивации и рынка, построение карьерных гипотез и планов перехода.',crit:{investigate:4,visible:3,help:5,deep:4,oneone:5,teach:5,novelty:4,ownership:4,autonomy:5,portable:5},dims:{help:1,investigate:1,teach:.9,social:.6,meaning:.7,autonomy:.7},risk:['public'],mvp:'Разберите карьерный трек 2 знакомых: соберите факты, выделите драйверы и предложите 3 гипотезы. Попросите оценить полезность разбора.'},
{name:'UX-исследователь',desc:'Интервью, наблюдение за поведением пользователей, поиск закономерностей и проблем продукта.',crit:{investigate:5,visible:4,help:3,deep:4,oneone:4,teach:4,novelty:5,ownership:4,autonomy:4,portable:4},dims:{investigate:1,order:.6,social:.5,novelty:.7,help:.4},risk:['public'],mvp:'Проведите 3 коридорных теста приложения: дайте человеку задачу, наблюдайте и фиксируйте точки заминки. Затем сгруппируйте наблюдения.'},
{name:'Специалист по внедрению ПО',desc:'Осваивает продукт, настраивает его у клиента, обучает пользователей и доводит запуск до рабочего состояния.',crit:{investigate:4,visible:5,help:4,deep:3,oneone:3,teach:5,novelty:4,ownership:5,autonomy:4,portable:3},dims:{teach:1,help:.7,investigate:.7,order:.5,social:.5},risk:['chaos'],mvp:'Возьмите незнакомый сервис, изучите его и проведите для знакомого короткое обучение: настройка, типовая задача, ответы на вопросы.'},
{name:'Системный / бизнес-аналитик',desc:'Разбирается, как устроены процессы или системы, собирает требования и превращает хаос в понятную модель.',crit:{investigate:5,visible:3,help:2,deep:4,oneone:3,teach:4,novelty:4,ownership:4,autonomy:4,portable:5},dims:{investigate:1,order:1,teach:.5,autonomy:.4},risk:['chaos'],mvp:'Опишите знакомый процесс «как есть»: участники, шаги, проблемы, входы и выходы. Затем предложите улучшенную схему.'},
{name:'Инженер по тестированию / QA',desc:'Ищет дефекты, воспроизводит ошибки, проверяет гипотезы и фиксирует результат по понятным критериям.',crit:{investigate:5,visible:5,help:1,deep:4,oneone:4,teach:2,novelty:4,ownership:5,autonomy:4,portable:5},dims:{investigate:1,order:1,craft:.35,autonomy:.4},risk:['routine'],mvp:'Возьмите приложение или устройство и составьте 20 тест-кейсов. Найдите 3 неоднозначных сценария и оформите баг-репорты.'},
{name:'CAD/CAM / 3D-моделирование',desc:'Точное моделирование объектов в профессиональном ПО с осязаемым результатом и понятным контуром задачи.',crit:{investigate:3,visible:5,help:2,deep:5,oneone:4,teach:2,novelty:3,ownership:5,autonomy:4,portable:4},dims:{craft:1,order:.9,investigate:.5,autonomy:.5},risk:['routine'],mvp:'Пройдите вводный модуль CAD и повторите 2 готовые модели. Оцените, нравится ли сам процесс точной работы, а не только результат.'},
{name:'Сервисный инженер / диагност оборудования',desc:'Диагностирует неисправности, ремонтирует или настраивает технику и проверяет результат.',crit:{investigate:5,visible:5,help:3,deep:4,oneone:4,teach:3,novelty:5,ownership:5,autonomy:4,portable:2},dims:{craft:1,investigate:1,order:.5,help:.4},risk:['unfair'],mvp:'Возьмите 2–3 технические неисправности: диагностика, гипотеза, действие, проверка. Ведите короткий журнал решений.'},
{name:'L&D / специалист по обучению',desc:'Диагностирует дефициты навыков, проектирует обучение, объясняет сложное и помогает людям освоить новое.',crit:{investigate:3,visible:3,help:5,deep:3,oneone:3,teach:5,novelty:4,ownership:4,autonomy:4,portable:4},dims:{teach:1,help:1,social:.6,order:.4},risk:['public'],mvp:'Сделайте микро-урок по теме, которую хорошо знаете. Проведите его для 2 людей и проверьте, смогли ли они выполнить задачу самостоятельно.'},
{name:'Onboarding / адаптация сотрудников',desc:'Помогает новым сотрудникам освоиться, разобраться в процессах и пройти первые месяцы.',crit:{investigate:3,visible:4,help:5,deep:3,oneone:4,teach:5,novelty:4,ownership:5,autonomy:3,portable:4},dims:{help:1,teach:.8,social:.8,order:.5},risk:['chaos'],mvp:'Составьте карту адаптации новичка: что человек должен понять за 1 день, 1 неделю, 1 месяц. Проверьте её на человеке, недавно вошедшем в сферу.'},
{name:'Customer Success / сопровождение клиентов',desc:'Помогает клиенту получить результат от продукта, диагностирует проблемы и координирует решение.',crit:{investigate:3,visible:4,help:5,deep:2,oneone:4,teach:4,novelty:4,ownership:4,autonomy:3,portable:5},dims:{help:1,social:1,teach:.5,order:.4},risk:['chaos','conflict'],mvp:'Выясните цель человека в знакомом сервисе, найдите 2 препятствия и предложите маршрут к результату. Оцените, нравится ли сопровождение.'},
{name:'Консультант один-на-один',desc:'Структурированные индивидуальные разговоры: исследование запроса и помощь человеку в формировании решений.',crit:{investigate:5,visible:3,help:5,deep:4,oneone:5,teach:3,novelty:5,ownership:4,autonomy:5,portable:5},dims:{help:1,investigate:.7,social:.5,meaning:.8},risk:['conflict'],mvp:'Проведите 3 структурированных разговора по модели GROW на бытовых целях и оцените собственное состояние после них.'},
{name:'Мастер-эксперт / частная практика',desc:'Штучная работа с конкретной проблемой клиента, где ценятся точность, ремесло и собственный стандарт качества.',crit:{investigate:4,visible:5,help:5,deep:5,oneone:5,teach:4,novelty:4,ownership:5,autonomy:5,portable:2},dims:{craft:1,help:.8,order:.8,autonomy:.8,recognition:.4},risk:['unfair'],mvp:'Выберите один узкий тип сложной задачи и протестируйте формат: диагностика, стандарт качества, объяснение клиенту, фиксация результата.'}
];